name: package_data_generator
description: Package data generator.
version: 0.1.0+1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  build: ^4.0.2
  pubspec_parse: ^1.5.0

dev_dependencies:
  very_good_analysis: ^10.0.0
