import 'package:coverde/src/entities/entities.dart';
import 'package:coverde/src/utils/utils.dart';
import 'package:http/http.dart' as http;
import 'package:io/ansi.dart';
import 'package:mason_logger/mason_logger.dart';
import 'package:mocktail/mocktail.dart';
import 'package:path/path.dart' as p;
import 'package:pub_semver/pub_semver.dart';
import 'package:test/test.dart';
import 'package:universal_io/universal_io.dart';

class _MockHttpClient extends Mock implements http.Client {}

final class _MockPackageVersionManagerDependencies extends Mock
    implements PackageVersionManagerDependencies {}

final class _MockLogger extends Mock implements Logger {}

final class _MockProgress extends Mock implements Progress {}

void main() {
  setUpAll(() {
    registerFallbackValue(Uri.parse(''));
  });

  group('$PackageVersionManager', () {
    late PackageVersionManagerDependencies dependencies;
    late PackageVersionManager packageVersionManager;

    setUp(() {
      dependencies = _MockPackageVersionManagerDependencies();
      packageVersionManager = PackageVersionManager(
        dependencies: dependencies,
      );
    });

    test('can be instantiated', () {
      expect(packageVersionManager, isA<PackageVersionManager>());
    });

    group('getGlobalPackageInstallationInfo', () {
      setUp(() {
        when(() => dependencies.baseUrl).thenReturn('');
      });

      test(
          'returns null '
          'if the lock file path resolves to a non-existent entity', () async {
        final tempDir = Directory.systemTemp.createTempSync();
        addTearDown(() => tempDir.deleteSync(recursive: true));
        when(() => dependencies.globalLockFilePath)
            .thenReturn(p.join(tempDir.path, 'pubspec.lock'));
        final globalPackageInstallationInfo =
            await packageVersionManager.getGlobalPackageInstallationInfo();
        expect(globalPackageInstallationInfo, isNull);
      });

      test(
          'returns null '
          'if the lock file path resolves to a non-file entity', () async {
        final tempDir = Directory.systemTemp.createTempSync();
        addTearDown(() => tempDir.deleteSync(recursive: true));
        when(() => dependencies.globalLockFilePath).thenReturn(tempDir.path);
        final globalPackageInstallationInfo =
            await packageVersionManager.getGlobalPackageInstallationInfo();
        expect(globalPackageInstallationInfo, isNull);
      });

      test(
          'returns null '
          'if the lock file does not contain the main package lock entry',
          () async {
        final tempDir = Directory.systemTemp.createTempSync();
        addTearDown(() => tempDir.deleteSync(recursive: true));
        final lockFilePath = p.join(tempDir.path, 'pubspec.lock');
        File(lockFilePath).writeAsStringSync('''
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  args:
    dependency: transitive
    description:
      name: args
      sha256: d0481093c50b1da8910eb0bb301626d4d8eb7284aa739614d2b394ee09e3ea04
      url: "https://pub.dev"
    source: hosted
    version: "2.7.0"
  async:
    dependency: transitive
    description:
      name: async
      sha256: "758e6d74e971c3e5aceb4110bfd6698efc7f501675bcfe0c775459a8140750eb"
      url: "https://pub.dev"
    source: hosted
    version: "2.13.0"
sdks:
  dart: ">=3.6.0 <4.0.0"
''');
        when(() => dependencies.globalLockFilePath).thenReturn(lockFilePath);
        final globalPackageInstallationInfo =
            await packageVersionManager.getGlobalPackageInstallationInfo();
        expect(globalPackageInstallationInfo, isNull);
      });

      test(
          'returns null '
          'if the lock file does not contain the Dart SDK version constraint',
          () async {
        final tempDir = Directory.systemTemp.createTempSync();
        addTearDown(() => tempDir.deleteSync(recursive: true));
        final lockFilePath = p.join(tempDir.path, 'pubspec.lock');
        File(lockFilePath).writeAsStringSync('''
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  args:
    dependency: transitive
    description:
      name: args
      sha256: d0481093c50b1da8910eb0bb301626d4d8eb7284aa739614d2b394ee09e3ea04
      url: "https://pub.dev"
    source: hosted
    version: "2.7.0"
  async:
    dependency: transitive
    description:
      name: async
      sha256: "758e6d74e971c3e5aceb4110bfd6698efc7f501675bcfe0c775459a8140750eb"
      url: "https://pub.dev"
    source: hosted
    version: "2.13.0"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: "2f5709ae4d3d59dd8f7cd309b4e023046b57d8a6c82130785d2b0e5868084e76"
      url: "https://pub.dev"
    source: hosted
    version: "1.19.1"
  coverde:
    dependency: "direct main"
    description:
      name: coverde
      sha256: "09d909f35accb2f1add449eba33b4afd835aad30ef039b34d6db65e52fe8fca8"
      url: "https://pub.dev"
    source: hosted
    version: "0.2.0+1"
  csslib:
    dependency: transitive
    description:
      name: csslib
      sha256: "09bad715f418841f976c77db72d5398dc1253c21fb9c0c7f0b0b985860b2d58e"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.2"
  file:
    dependency: transitive
    description:
      name: file
      sha256: "1b92bec4fc2a72f59a8e15af5f52cd441e4a7860b49499d69dfa817af20e925d"
      url: "https://pub.dev"
    source: hosted
    version: "6.1.4"
''');
        when(() => dependencies.globalLockFilePath).thenReturn(lockFilePath);
        final globalPackageInstallationInfo =
            await packageVersionManager.getGlobalPackageInstallationInfo();
        expect(globalPackageInstallationInfo, isNull);
      });

      test('returns the global package installation info ', () async {
        final tempDir = Directory.systemTemp.createTempSync();
        addTearDown(() => tempDir.deleteSync(recursive: true));
        final lockFilePath = p.join(tempDir.path, 'pubspec.lock');
        File(lockFilePath).writeAsStringSync('''
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  args:
    dependency: transitive
    description:
      name: args
      sha256: d0481093c50b1da8910eb0bb301626d4d8eb7284aa739614d2b394ee09e3ea04
      url: "https://pub.dev"
    source: hosted
    version: "2.7.0"
  async:
    dependency: transitive
    description:
      name: async
      sha256: "758e6d74e971c3e5aceb4110bfd6698efc7f501675bcfe0c775459a8140750eb"
      url: "https://pub.dev"
    source: hosted
    version: "2.13.0"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: "2f5709ae4d3d59dd8f7cd309b4e023046b57d8a6c82130785d2b0e5868084e76"
      url: "https://pub.dev"
    source: hosted
    version: "1.19.1"
  coverde:
    dependency: "direct main"
    description:
      name: coverde
      sha256: "09d909f35accb2f1add449eba33b4afd835aad30ef039b34d6db65e52fe8fca8"
      url: "https://pub.dev"
    source: hosted
    version: "0.2.0+1"
  csslib:
    dependency: transitive
    description:
      name: csslib
      sha256: "09bad715f418841f976c77db72d5398dc1253c21fb9c0c7f0b0b985860b2d58e"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.2"
  file:
    dependency: transitive
    description:
      name: file
      sha256: "1b92bec4fc2a72f59a8e15af5f52cd441e4a7860b49499d69dfa817af20e925d"
      url: "https://pub.dev"
    source: hosted
    version: "6.1.4"
  html:
    dependency: transitive
    description:
      name: html
      sha256: "6d1264f2dffa1b1101c25a91dff0dc2daee4c18e87cd8538729773c073dbf602"
      url: "https://pub.dev"
    source: hosted
    version: "0.15.6"
  http:
    dependency: transitive
    description:
      name: http
      sha256: "87721a4a50b19c7f1d49001e51409bddc46303966ce89a65af4f4e6004896412"
      url: "https://pub.dev"
    source: hosted
    version: "1.6.0"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      sha256: "178d74305e7866013777bab2c3d8726205dc5a4dd935297175b19a23a2e66571"
      url: "https://pub.dev"
    source: hosted
    version: "4.1.2"
  io:
    dependency: transitive
    description:
      name: io
      sha256: dfd5a80599cf0165756e3181807ed3e77daf6dd4137caaad72d0b7931597650b
      url: "https://pub.dev"
    source: hosted
    version: "1.0.5"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      sha256: "1ce844379ca14835a50d2f019a3099f419082cfdd231cd86a142af94dd5c6bb1"
      url: "https://pub.dev"
    source: hosted
    version: "4.9.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: "23f08335362185a5ea2ad3a4e597f1375e78bce8a040df5c600c8d3552ef2394"
      url: "https://pub.dev"
    source: hosted
    version: "1.17.0"
  path:
    dependency: transitive
    description:
      name: path
      sha256: "75cca69d1490965be98c73ceaea117e8a04dd21217b37b292c9ddbec0d955bc5"
      url: "https://pub.dev"
    source: hosted
    version: "1.9.1"
  platform:
    dependency: transitive
    description:
      name: platform
      sha256: "5d6b1b0036a5f331ebc77c850ebc8506cbc1e9416c27e59b439f917a902a4984"
      url: "https://pub.dev"
    source: hosted
    version: "3.1.6"
  process:
    dependency: transitive
    description:
      name: process
      sha256: "53fd8db9cec1d37b0574e12f07520d582019cb6c44abf5479a01505099a34a09"
      url: "https://pub.dev"
    source: hosted
    version: "4.2.4"
  pub_semver:
    dependency: transitive
    description:
      name: pub_semver
      sha256: "5bfcf68ca79ef689f8990d1160781b4bad40a3bd5e5218ad4076ddb7f4081585"
      url: "https://pub.dev"
    source: hosted
    version: "2.2.0"
  pub_updater:
    dependency: transitive
    description:
      name: pub_updater
      sha256: b06600619c8c219065a548f8f7c192b3e080beff95488ed692780f48f69c0625
      url: "https://pub.dev"
    source: hosted
    version: "0.3.1"
  source_span:
    dependency: transitive
    description:
      name: source_span
      sha256: "254ee5351d6cb365c859e20ee823c3bb479bf4a293c22d17a9f1bf144ce86f7c"
      url: "https://pub.dev"
    source: hosted
    version: "1.10.1"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      sha256: "921cd31725b72fe181906c6a94d987c78e3b98c2e205b397ea399d4054872b43"
      url: "https://pub.dev"
    source: hosted
    version: "1.4.1"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      sha256: "7f554798625ea768a7518313e58f83891c7f5024f88e46e7182a4558850a4b8e"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.2"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      sha256: f9049c039ebfeb4cf7a7104a675823cd72dba8297f264b6637062516699fa006
      url: "https://pub.dev"
    source: hosted
    version: "1.4.0"
  universal_io:
    dependency: transitive
    description:
      name: universal_io
      sha256: f63cbc48103236abf48e345e07a03ce5757ea86285ed313a6a032596ed9301e2
      url: "https://pub.dev"
    source: hosted
    version: "2.3.1"
  web:
    dependency: transitive
    description:
      name: web
      sha256: "868d88a33d8a87b18ffc05f9f030ba328ffefba92d6c127917a2ba740f9cfe4a"
      url: "https://pub.dev"
    source: hosted
    version: "1.1.1"
sdks:
  dart: ">=3.6.0 <4.0.0"
''');
        when(() => dependencies.globalLockFilePath).thenReturn(lockFilePath);
        final globalPackageInstallationInfo =
            await packageVersionManager.getGlobalPackageInstallationInfo();
        expect(
          globalPackageInstallationInfo,
          PackageVersioningInfo(
            packageName: 'coverde',
            packageVersion: Version.parse('0.2.0+1'),
            dartVersionConstraint: VersionConstraint.parse('>=3.6.0 <4.0.0'),
          ),
        );
      });
    });

    group('getRemotePackageVersioningInfos', () {
      late http.Client httpClient;

      setUp(() {
        httpClient = _MockHttpClient();
        when(() => dependencies.httpClient).thenReturn(httpClient);
        when(() => dependencies.baseUrl).thenReturn('https://example.com');
      });

      test('throws an exception if the remote package info request fails',
          () async {
        when(() => httpClient.get(any())).thenAnswer(
          (_) async => http.Response(
            'Failed to get remote package info',
            500,
          ),
        );
        expect(
          () =>
              packageVersionManager.getRemotePackageVersioningInfos('coverde'),
          throwsA(isA<Exception>()),
        );
      });

      test('returns the remote package installation infos', () async {
        when(() => httpClient.get(any())).thenAnswer(
          (_) async => http.Response(
            '''
{
    "name": "coverde",
    "latest": {
        "version": "0.2.0+2",
        "pubspec": {
            "name": "coverde",
            "description": "A CLI for basic coverage trace files manipulation. Validate minimum coverage, filter trace files data by tested file paths and generate HTML coverage reports.",
            "version": "0.2.0+2",
            "homepage": "https://github.com/mrverdant13/coverde",
            "repository": "https://github.com/mrverdant13/coverde/tree/main/packages/coverde_cli",
            "issue_tracker": "https://github.com/mrverdant13/coverde/issues",
            "topics": [
                "test",
                "testing",
                "coverage",
                "lcov"
            ],
            "screenshots": [
                {
                    "description": "Coverage report example (directory)",
                    "path": "doc/report_directory_example.png"
                },
                {
                    "description": "Coverage report example (file)",
                    "path": "doc/report_file_example.png"
                },
                {
                    "description": "Coverage check example (passing)",
                    "path": "doc/check_result_pass.png"
                },
                {
                    "description": "Coverage check example (failing)",
                    "path": "doc/check_result_fail.png"
                }
            ],
            "environment": {
                "sdk": ">=3.0.0 <4.0.0"
            },
            "dependencies": {
                "args": "^2.4.2",
                "collection": "^1.18.0",
                "html": "^0.15.4",
                "io": "^1.0.4",
                "meta": "^1.9.1",
                "path": "^1.8.3",
                "process": "^4.2.4",
                "pub_updater": "^0.3.1",
                "universal_io": "^2.2.2"
            },
            "dev_dependencies": {
                "build": "^2.4.1",
                "build_config": "^1.1.1",
                "build_runner": "^2.4.6",
                "build_verify": "^3.1.0",
                "csslib": "^1.0.0",
                "mocktail": "^1.0.0",
                "pubspec_parse": "^1.2.3",
                "test": "^1.24.6",
                "very_good_analysis": "^5.0.0+1",
                "package_assets_generator": {
                    "path": "../package_assets_generator"
                },
                "package_data_generator": {
                    "path": "../package_data_generator"
                }
            },
            "executables": {
                "coverde": null
            }
        },
        "archive_url": "https://pub.dev/api/archives/coverde-0.2.0%2B2.tar.gz",
        "archive_sha256": "09d909f35accb2f1add449eba33b4afd835aad30ef039b34d6db65e52fe8fca8",
        "published": "2023-08-18T07:52:19.455101Z"
    },
    "versions": [
        {
            "version": "0.1.0",
            "pubspec": {
                "name": "coverde",
                "description": "A CLI for basic coverage trace files manipulation. Validate minimum coverage, filter trace files data by tested file paths and generate HTML coverage reports.",
                "version": "0.1.0",
                "homepage": "https://github.com/mrverdant13/coverde",
                "repository": "https://github.com/mrverdant13/coverde",
                "issue_tracker": "https://github.com/mrverdant13/coverde/issues",
                "environment": {
                    "sdk": ">=2.14.4 <3.0.0"
                },
                "dependencies": {
                    "args": "^2.3.0",
                    "collection": "^1.15.0",
                    "html": "^0.15.0",
                    "io": "^1.0.3",
                    "meta": "^1.7.0",
                    "path": "^1.8.0",
                    "process": "^4.2.4",
                    "pub_updater": "^0.2.2",
                    "pubspec_parse": "^1.1.0",
                    "universal_io": "^2.0.4"
                },
                "dev_dependencies": {
                    "build": "^2.1.1",
                    "build_config": "^1.0.0",
                    "build_runner": "^2.1.5",
                    "build_verify": "^2.0.0",
                    "csslib": "^0.17.1",
                    "mocktail": "^0.2.0",
                    "test": "^1.19.3",
                    "very_good_analysis": "^2.4.0"
                },
                "executables": {
                    "coverde": null
                }
            },
            "archive_url": "https://pub.dev/api/archives/coverde-0.1.0.tar.gz",
            "archive_sha256": "9b998d9f8f4110d14548b5455c26a428c2739c5634acbf7003eff5c937469f29",
            "published": "2021-12-02T05:53:30.160920Z"
        },
        {
            "version": "0.1.0+1",
            "pubspec": {
                "name": "coverde",
                "description": "A CLI for basic coverage trace files manipulation. Validate minimum coverage, filter trace files data by tested file paths and generate HTML coverage reports.",
                "version": "0.1.0+1",
                "homepage": "https://github.com/mrverdant13/coverde",
                "repository": "https://github.com/mrverdant13/coverde",
                "issue_tracker": "https://github.com/mrverdant13/coverde/issues",
                "environment": {
                    "sdk": ">=2.14.4 <3.0.0"
                },
                "dependencies": {
                    "args": "^2.3.0",
                    "collection": "^1.15.0",
                    "html": "^0.15.0",
                    "io": "^1.0.3",
                    "meta": "^1.7.0",
                    "path": "^1.8.0",
                    "process": "^4.2.4",
                    "pub_updater": "^0.2.2",
                    "pubspec_parse": "^1.1.0",
                    "universal_io": "^2.0.4"
                },
                "dev_dependencies": {
                    "build": "^2.1.1",
                    "build_config": "^1.0.0",
                    "build_runner": "^2.1.5",
                    "build_verify": "^2.0.0",
                    "csslib": "^0.17.1",
                    "mocktail": "^0.2.0",
                    "test": "^1.19.3",
                    "very_good_analysis": "^2.4.0"
                },
                "executables": {
                    "coverde": null
                }
            },
            "archive_url": "https://pub.dev/api/archives/coverde-0.1.0%2B1.tar.gz",
            "archive_sha256": "816d220df3a27e9e9f087388221f1ad6fb34311c6e1c6c1105582779445298cb",
            "published": "2021-12-02T07:38:45.581319Z"
        },
        {
            "version": "0.2.0",
            "retracted": true,
            "pubspec": {
                "name": "coverde",
                "description": "A CLI for basic coverage trace files manipulation. Validate minimum coverage, filter trace files data by tested file paths and generate HTML coverage reports.",
                "version": "0.2.0",
                "homepage": "https://github.com/mrverdant13/coverde",
                "repository": "https://github.com/mrverdant13/coverde/tree/main/packages/coverde_cli",
                "issue_tracker": "https://github.com/mrverdant13/coverde/issues",
                "environment": {
                    "sdk": ">=3.0.0 <4.0.0"
                },
                "dependencies": {
                    "args": "^2.4.2",
                    "collection": "^1.18.0",
                    "html": "^0.15.4",
                    "io": "^1.0.4",
                    "meta": "^1.9.1",
                    "path": "^1.8.3",
                    "process": "^4.2.4",
                    "pub_updater": "^0.3.1",
                    "universal_io": "^2.2.2"
                },
                "dev_dependencies": {
                    "build": "^2.4.1",
                    "build_config": "^1.1.1",
                    "build_runner": "^2.4.6",
                    "build_verify": "^3.1.0",
                    "csslib": "^1.0.0",
                    "mocktail": "^1.0.0",
                    "pubspec_parse": "^1.2.3",
                    "test": "^1.24.6",
                    "very_good_analysis": "^5.0.0+1",
                    "package_assets_generator": {
                        "path": "../package_assets_generator"
                    },
                    "package_data_generator": {
                        "path": "../package_data_generator"
                    }
                },
                "executables": {
                    "coverde": null
                }
            },
            "archive_url": "https://pub.dev/api/archives/coverde-0.2.0.tar.gz",
            "archive_sha256": "4f5adc5a9d74874846f2f880d2ba54a03b7635843d94560d481427bbcfee46eb",
            "published": "2023-08-14T08:13:10.084167Z"
        },
        {
            "version": "0.2.0+1",
            "retracted": true,
            "pubspec": {
                "name": "coverde",
                "description": "A CLI for basic coverage trace files manipulation. Validate minimum coverage, filter trace files data by tested file paths and generate HTML coverage reports.",
                "version": "0.2.0+1",
                "homepage": "https://github.com/mrverdant13/coverde",
                "repository": "https://github.com/mrverdant13/coverde/tree/main/packages/coverde_cli",
                "issue_tracker": "https://github.com/mrverdant13/coverde/issues",
                "environment": {
                    "sdk": ">=3.0.0 <4.0.0"
                },
                "dependencies": {
                    "args": "^2.4.2",
                    "collection": "^1.18.0",
                    "html": "^0.15.4",
                    "io": "^1.0.4",
                    "meta": "^1.9.1",
                    "path": "^1.8.3",
                    "process": "^4.2.4",
                    "pub_updater": "^0.3.1",
                    "universal_io": "^2.2.2"
                },
                "dev_dependencies": {
                    "build": "^2.4.1",
                    "build_config": "^1.1.1",
                    "build_runner": "^2.4.6",
                    "build_verify": "^3.1.0",
                    "csslib": "^1.0.0",
                    "mocktail": "^1.0.0",
                    "pubspec_parse": "^1.2.3",
                    "test": "^1.24.6",
                    "very_good_analysis": "^5.0.0+1",
                    "package_assets_generator": {
                        "path": "../package_assets_generator"
                    },
                    "package_data_generator": {
                        "path": "../package_data_generator"
                    }
                },
                "executables": {
                    "coverde": null
                }
            },
            "archive_url": "https://pub.dev/api/archives/coverde-0.2.0%2B1.tar.gz",
            "archive_sha256": "f3577d4b9dd44cff7b280c891ec0ed19fb0ca7cc3ed6e3e24c17d01b3c12384c",
            "published": "2023-08-14T08:52:19.247838Z"
        },
        {
            "version": "0.2.0+2",
            "pubspec": {
                "name": "coverde",
                "description": "A CLI for basic coverage trace files manipulation. Validate minimum coverage, filter trace files data by tested file paths and generate HTML coverage reports.",
                "version": "0.2.0+2",
                "homepage": "https://github.com/mrverdant13/coverde",
                "repository": "https://github.com/mrverdant13/coverde/tree/main/packages/coverde_cli",
                "issue_tracker": "https://github.com/mrverdant13/coverde/issues",
                "topics": [
                    "test",
                    "testing",
                    "coverage",
                    "lcov"
                ],
                "screenshots": [
                    {
                        "description": "Coverage report example (directory)",
                        "path": "doc/report_directory_example.png"
                    },
                    {
                        "description": "Coverage report example (file)",
                        "path": "doc/report_file_example.png"
                    },
                    {
                        "description": "Coverage check example (passing)",
                        "path": "doc/check_result_pass.png"
                    },
                    {
                        "description": "Coverage check example (failing)",
                        "path": "doc/check_result_fail.png"
                    }
                ],
                "environment": {
                    "sdk": ">=3.0.0 <4.0.0"
                },
                "dependencies": {
                    "args": "^2.4.2",
                    "collection": "^1.18.0",
                    "html": "^0.15.4",
                    "io": "^1.0.4",
                    "meta": "^1.9.1",
                    "path": "^1.8.3",
                    "process": "^4.2.4",
                    "pub_updater": "^0.3.1",
                    "universal_io": "^2.2.2"
                },
                "dev_dependencies": {
                    "build": "^2.4.1",
                    "build_config": "^1.1.1",
                    "build_runner": "^2.4.6",
                    "build_verify": "^3.1.0",
                    "csslib": "^1.0.0",
                    "mocktail": "^1.0.0",
                    "pubspec_parse": "^1.2.3",
                    "test": "^1.24.6",
                    "very_good_analysis": "^5.0.0+1",
                    "package_assets_generator": {
                        "path": "../package_assets_generator"
                    },
                    "package_data_generator": {
                        "path": "../package_data_generator"
                    }
                },
                "executables": {
                    "coverde": null
                }
            },
            "archive_url": "https://pub.dev/api/archives/coverde-0.2.0%2B2.tar.gz",
            "archive_sha256": "09d909f35accb2f1add449eba33b4afd835aad30ef039b34d6db65e52fe8fca8",
            "published": "2023-08-18T07:52:19.455101Z"
        }
    ]
}
            ''',
            HttpStatus.ok,
          ),
        );
        final remotePackageInstallationInfos = await packageVersionManager
            .getRemotePackageVersioningInfos('coverde');
        expect(
          remotePackageInstallationInfos,
          [
            PackageVersioningInfo(
              packageName: 'coverde',
              packageVersion: Version.parse('0.2.0+2'),
              dartVersionConstraint: VersionConstraint.parse('>=3.0.0 <4.0.0'),
            ),
            PackageVersioningInfo(
              packageName: 'coverde',
              packageVersion: Version.parse('0.2.0+1'),
              dartVersionConstraint: VersionConstraint.parse('>=3.0.0 <4.0.0'),
            ),
            PackageVersioningInfo(
              packageName: 'coverde',
              packageVersion: Version.parse('0.2.0'),
              dartVersionConstraint: VersionConstraint.parse('>=3.0.0 <4.0.0'),
            ),
            PackageVersioningInfo(
              packageName: 'coverde',
              packageVersion: Version.parse('0.1.0+1'),
              dartVersionConstraint: VersionConstraint.parse('>=2.14.4 <3.0.0'),
            ),
            PackageVersioningInfo(
              packageName: 'coverde',
              packageVersion: Version.parse('0.1.0'),
              dartVersionConstraint: VersionConstraint.parse('>=2.14.4 <3.0.0'),
            ),
          ],
        );
      });
    });

    group('promptUpdate', () {
      late String lockFilePath;
      late http.Client httpClient;
      late Logger logger;

      setUp(() {
        final tempDir = Directory.systemTemp.createTempSync();
        addTearDown(() => tempDir.deleteSync(recursive: true));
        lockFilePath = p.join(tempDir.path, 'pubspec.lock');
        when(() => dependencies.baseUrl).thenReturn('https://example.com');
        when(() => dependencies.globalLockFilePath).thenReturn(lockFilePath);
        httpClient = _MockHttpClient();
        when(() => dependencies.httpClient).thenReturn(httpClient);
        logger = _MockLogger();
        when(() => dependencies.logger).thenReturn(logger);
        when(() => dependencies.rawDartVersion).thenReturn('3.6.0');
      });

      test(
          'prompts the user to update the package '
          'if there is a compatible newer version', () async {
        File(lockFilePath).writeAsStringSync('''
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  args:
    dependency: transitive
    description:
      name: args
      sha256: d0481093c50b1da8910eb0bb301626d4d8eb7284aa739614d2b394ee09e3ea04
      url: "https://pub.dev"
    source: hosted
    version: "2.7.0"
  async:
    dependency: transitive
    description:
      name: async
      sha256: "758e6d74e971c3e5aceb4110bfd6698efc7f501675bcfe0c775459a8140750eb"
      url: "https://pub.dev"
    source: hosted
    version: "2.13.0"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: "2f5709ae4d3d59dd8f7cd309b4e023046b57d8a6c82130785d2b0e5868084e76"
      url: "https://pub.dev"
    source: hosted
    version: "1.19.1"
  coverde:
    dependency: "direct main"
    description:
      name: coverde
      sha256: "09d909f35accb2f1add449eba33b4afd835aad30ef039b34d6db65e52fe8fca8"
      url: "https://pub.dev"
    source: hosted
    version: "0.2.0+1"
  csslib:
    dependency: transitive
    description:
      name: csslib
      sha256: "09bad715f418841f976c77db72d5398dc1253c21fb9c0c7f0b0b985860b2d58e"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.2"
  file:
    dependency: transitive
    description:
      name: file
      sha256: "1b92bec4fc2a72f59a8e15af5f52cd441e4a7860b49499d69dfa817af20e925d"
      url: "https://pub.dev"
    source: hosted
    version: "6.1.4"
  html:
    dependency: transitive
    description:
      name: html
      sha256: "6d1264f2dffa1b1101c25a91dff0dc2daee4c18e87cd8538729773c073dbf602"
      url: "https://pub.dev"
    source: hosted
    version: "0.15.6"
  http:
    dependency: transitive
    description:
      name: http
      sha256: "87721a4a50b19c7f1d49001e51409bddc46303966ce89a65af4f4e6004896412"
      url: "https://pub.dev"
    source: hosted
    version: "1.6.0"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      sha256: "178d74305e7866013777bab2c3d8726205dc5a4dd935297175b19a23a2e66571"
      url: "https://pub.dev"
    source: hosted
    version: "4.1.2"
  io:
    dependency: transitive
    description:
      name: io
      sha256: dfd5a80599cf0165756e3181807ed3e77daf6dd4137caaad72d0b7931597650b
      url: "https://pub.dev"
    source: hosted
    version: "1.0.5"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      sha256: "1ce844379ca14835a50d2f019a3099f419082cfdd231cd86a142af94dd5c6bb1"
      url: "https://pub.dev"
    source: hosted
    version: "4.9.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: "23f08335362185a5ea2ad3a4e597f1375e78bce8a040df5c600c8d3552ef2394"
      url: "https://pub.dev"
    source: hosted
    version: "1.17.0"
  path:
    dependency: transitive
    description:
      name: path
      sha256: "75cca69d1490965be98c73ceaea117e8a04dd21217b37b292c9ddbec0d955bc5"
      url: "https://pub.dev"
    source: hosted
    version: "1.9.1"
  platform:
    dependency: transitive
    description:
      name: platform
      sha256: "5d6b1b0036a5f331ebc77c850ebc8506cbc1e9416c27e59b439f917a902a4984"
      url: "https://pub.dev"
    source: hosted
    version: "3.1.6"
  process:
    dependency: transitive
    description:
      name: process
      sha256: "53fd8db9cec1d37b0574e12f07520d582019cb6c44abf5479a01505099a34a09"
      url: "https://pub.dev"
    source: hosted
    version: "4.2.4"
  pub_semver:
    dependency: transitive
    description:
      name: pub_semver
      sha256: "5bfcf68ca79ef689f8990d1160781b4bad40a3bd5e5218ad4076ddb7f4081585"
      url: "https://pub.dev"
    source: hosted
    version: "2.2.0"
  pub_updater:
    dependency: transitive
    description:
      name: pub_updater
      sha256: b06600619c8c219065a548f8f7c192b3e080beff95488ed692780f48f69c0625
      url: "https://pub.dev"
    source: hosted
    version: "0.3.1"
  source_span:
    dependency: transitive
    description:
      name: source_span
      sha256: "254ee5351d6cb365c859e20ee823c3bb479bf4a293c22d17a9f1bf144ce86f7c"
      url: "https://pub.dev"
    source: hosted
    version: "1.10.1"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      sha256: "921cd31725b72fe181906c6a94d987c78e3b98c2e205b397ea399d4054872b43"
      url: "https://pub.dev"
    source: hosted
    version: "1.4.1"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      sha256: "7f554798625ea768a7518313e58f83891c7f5024f88e46e7182a4558850a4b8e"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.2"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      sha256: f9049c039ebfeb4cf7a7104a675823cd72dba8297f264b6637062516699fa006
      url: "https://pub.dev"
    source: hosted
    version: "1.4.0"
  universal_io:
    dependency: transitive
    description:
      name: universal_io
      sha256: f63cbc48103236abf48e345e07a03ce5757ea86285ed313a6a032596ed9301e2
      url: "https://pub.dev"
    source: hosted
    version: "2.3.1"
  web:
    dependency: transitive
    description:
      name: web
      sha256: "868d88a33d8a87b18ffc05f9f030ba328ffefba92d6c127917a2ba740f9cfe4a"
      url: "https://pub.dev"
    source: hosted
    version: "1.1.1"
sdks:
  dart: ">=3.6.0 <4.0.0"
''');
        when(() => httpClient.get(any())).thenAnswer(
          (_) => Future.delayed(
            const Duration(milliseconds: 150),
            () async => http.Response(
              '''
{
    "name": "coverde",
    "latest": {
        "version": "0.2.0+2",
        "pubspec": {
            "name": "coverde",
            "description": "A CLI for basic coverage trace files manipulation. Validate minimum coverage, filter trace files data by tested file paths and generate HTML coverage reports.",
            "version": "0.2.0+2",
            "homepage": "https://github.com/mrverdant13/coverde",
            "repository": "https://github.com/mrverdant13/coverde/tree/main/packages/coverde_cli",
            "issue_tracker": "https://github.com/mrverdant13/coverde/issues",
            "topics": [
                "test",
                "testing",
                "coverage",
                "lcov"
            ],
            "screenshots": [
                {
                    "description": "Coverage report example (directory)",
                    "path": "doc/report_directory_example.png"
                },
                {
                    "description": "Coverage report example (file)",
                    "path": "doc/report_file_example.png"
                },
                {
                    "description": "Coverage check example (passing)",
                    "path": "doc/check_result_pass.png"
                },
                {
                    "description": "Coverage check example (failing)",
                    "path": "doc/check_result_fail.png"
                }
            ],
            "environment": {
                "sdk": ">=3.0.0 <4.0.0"
            },
            "dependencies": {
                "args": "^2.4.2",
                "collection": "^1.18.0",
                "html": "^0.15.4",
                "io": "^1.0.4",
                "meta": "^1.9.1",
                "path": "^1.8.3",
                "process": "^4.2.4",
                "pub_updater": "^0.3.1",
                "universal_io": "^2.2.2"
            },
            "dev_dependencies": {
                "build": "^2.4.1",
                "build_config": "^1.1.1",
                "build_runner": "^2.4.6",
                "build_verify": "^3.1.0",
                "csslib": "^1.0.0",
                "mocktail": "^1.0.0",
                "pubspec_parse": "^1.2.3",
                "test": "^1.24.6",
                "very_good_analysis": "^5.0.0+1",
                "package_assets_generator": {
                    "path": "../package_assets_generator"
                },
                "package_data_generator": {
                    "path": "../package_data_generator"
                }
            },
            "executables": {
                "coverde": null
            }
        },
        "archive_url": "https://pub.dev/api/archives/coverde-0.2.0%2B2.tar.gz",
        "archive_sha256": "09d909f35accb2f1add449eba33b4afd835aad30ef039b34d6db65e52fe8fca8",
        "published": "2023-08-18T07:52:19.455101Z"
    },
    "versions": [
        {
            "version": "0.1.0",
            "pubspec": {
                "name": "coverde",
                "description": "A CLI for basic coverage trace files manipulation. Validate minimum coverage, filter trace files data by tested file paths and generate HTML coverage reports.",
                "version": "0.1.0",
                "homepage": "https://github.com/mrverdant13/coverde",
                "repository": "https://github.com/mrverdant13/coverde",
                "issue_tracker": "https://github.com/mrverdant13/coverde/issues",
                "environment": {
                    "sdk": ">=2.14.4 <3.0.0"
                },
                "dependencies": {
                    "args": "^2.3.0",
                    "collection": "^1.15.0",
                    "html": "^0.15.0",
                    "io": "^1.0.3",
                    "meta": "^1.7.0",
                    "path": "^1.8.0",
                    "process": "^4.2.4",
                    "pub_updater": "^0.2.2",
                    "pubspec_parse": "^1.1.0",
                    "universal_io": "^2.0.4"
                },
                "dev_dependencies": {
                    "build": "^2.1.1",
                    "build_config": "^1.0.0",
                    "build_runner": "^2.1.5",
                    "build_verify": "^2.0.0",
                    "csslib": "^0.17.1",
                    "mocktail": "^0.2.0",
                    "test": "^1.19.3",
                    "very_good_analysis": "^2.4.0"
                },
                "executables": {
                    "coverde": null
                }
            },
            "archive_url": "https://pub.dev/api/archives/coverde-0.1.0.tar.gz",
            "archive_sha256": "9b998d9f8f4110d14548b5455c26a428c2739c5634acbf7003eff5c937469f29",
            "published": "2021-12-02T05:53:30.160920Z"
        },
        {
            "version": "0.1.0+1",
            "pubspec": {
                "name": "coverde",
                "description": "A CLI for basic coverage trace files manipulation. Validate minimum coverage, filter trace files data by tested file paths and generate HTML coverage reports.",
                "version": "0.1.0+1",
                "homepage": "https://github.com/mrverdant13/coverde",
                "repository": "https://github.com/mrverdant13/coverde",
                "issue_tracker": "https://github.com/mrverdant13/coverde/issues",
                "environment": {
                    "sdk": ">=2.14.4 <3.0.0"
                },
                "dependencies": {
                    "args": "^2.3.0",
                    "collection": "^1.15.0",
                    "html": "^0.15.0",
                    "io": "^1.0.3",
                    "meta": "^1.7.0",
                    "path": "^1.8.0",
                    "process": "^4.2.4",
                    "pub_updater": "^0.2.2",
                    "pubspec_parse": "^1.1.0",
                    "universal_io": "^2.0.4"
                },
                "dev_dependencies": {
                    "build": "^2.1.1",
                    "build_config": "^1.0.0",
                    "build_runner": "^2.1.5",
                    "build_verify": "^2.0.0",
                    "csslib": "^0.17.1",
                    "mocktail": "^0.2.0",
                    "test": "^1.19.3",
                    "very_good_analysis": "^2.4.0"
                },
                "executables": {
                    "coverde": null
                }
            },
            "archive_url": "https://pub.dev/api/archives/coverde-0.1.0%2B1.tar.gz",
            "archive_sha256": "816d220df3a27e9e9f087388221f1ad6fb34311c6e1c6c1105582779445298cb",
            "published": "2021-12-02T07:38:45.581319Z"
        },
        {
            "version": "0.2.0",
            "retracted": true,
            "pubspec": {
                "name": "coverde",
                "description": "A CLI for basic coverage trace files manipulation. Validate minimum coverage, filter trace files data by tested file paths and generate HTML coverage reports.",
                "version": "0.2.0",
                "homepage": "https://github.com/mrverdant13/coverde",
                "repository": "https://github.com/mrverdant13/coverde/tree/main/packages/coverde_cli",
                "issue_tracker": "https://github.com/mrverdant13/coverde/issues",
                "environment": {
                    "sdk": ">=3.0.0 <4.0.0"
                },
                "dependencies": {
                    "args": "^2.4.2",
                    "collection": "^1.18.0",
                    "html": "^0.15.4",
                    "io": "^1.0.4",
                    "meta": "^1.9.1",
                    "path": "^1.8.3",
                    "process": "^4.2.4",
                    "pub_updater": "^0.3.1",
                    "universal_io": "^2.2.2"
                },
                "dev_dependencies": {
                    "build": "^2.4.1",
                    "build_config": "^1.1.1",
                    "build_runner": "^2.4.6",
                    "build_verify": "^3.1.0",
                    "csslib": "^1.0.0",
                    "mocktail": "^1.0.0",
                    "pubspec_parse": "^1.2.3",
                    "test": "^1.24.6",
                    "very_good_analysis": "^5.0.0+1",
                    "package_assets_generator": {
                        "path": "../package_assets_generator"
                    },
                    "package_data_generator": {
                        "path": "../package_data_generator"
                    }
                },
                "executables": {
                    "coverde": null
                }
            },
            "archive_url": "https://pub.dev/api/archives/coverde-0.2.0.tar.gz",
            "archive_sha256": "4f5adc5a9d74874846f2f880d2ba54a03b7635843d94560d481427bbcfee46eb",
            "published": "2023-08-14T08:13:10.084167Z"
        },
        {
            "version": "0.2.0+1",
            "retracted": true,
            "pubspec": {
                "name": "coverde",
                "description": "A CLI for basic coverage trace files manipulation. Validate minimum coverage, filter trace files data by tested file paths and generate HTML coverage reports.",
                "version": "0.2.0+1",
                "homepage": "https://github.com/mrverdant13/coverde",
                "repository": "https://github.com/mrverdant13/coverde/tree/main/packages/coverde_cli",
                "issue_tracker": "https://github.com/mrverdant13/coverde/issues",
                "environment": {
                    "sdk": ">=3.0.0 <4.0.0"
                },
                "dependencies": {
                    "args": "^2.4.2",
                    "collection": "^1.18.0",
                    "html": "^0.15.4",
                    "io": "^1.0.4",
                    "meta": "^1.9.1",
                    "path": "^1.8.3",
                    "process": "^4.2.4",
                    "pub_updater": "^0.3.1",
                    "universal_io": "^2.2.2"
                },
                "dev_dependencies": {
                    "build": "^2.4.1",
                    "build_config": "^1.1.1",
                    "build_runner": "^2.4.6",
                    "build_verify": "^3.1.0",
                    "csslib": "^1.0.0",
                    "mocktail": "^1.0.0",
                    "pubspec_parse": "^1.2.3",
                    "test": "^1.24.6",
                    "very_good_analysis": "^5.0.0+1",
                    "package_assets_generator": {
                        "path": "../package_assets_generator"
                    },
                    "package_data_generator": {
                        "path": "../package_data_generator"
                    }
                },
                "executables": {
                    "coverde": null
                }
            },
            "archive_url": "https://pub.dev/api/archives/coverde-0.2.0%2B1.tar.gz",
            "archive_sha256": "f3577d4b9dd44cff7b280c891ec0ed19fb0ca7cc3ed6e3e24c17d01b3c12384c",
            "published": "2023-08-14T08:52:19.247838Z"
        },
        {
            "version": "0.2.0+2",
            "pubspec": {
                "name": "coverde",
                "description": "A CLI for basic coverage trace files manipulation. Validate minimum coverage, filter trace files data by tested file paths and generate HTML coverage reports.",
                "version": "0.2.0+2",
                "homepage": "https://github.com/mrverdant13/coverde",
                "repository": "https://github.com/mrverdant13/coverde/tree/main/packages/coverde_cli",
                "issue_tracker": "https://github.com/mrverdant13/coverde/issues",
                "topics": [
                    "test",
                    "testing",
                    "coverage",
                    "lcov"
                ],
                "screenshots": [
                    {
                        "description": "Coverage report example (directory)",
                        "path": "doc/report_directory_example.png"
                    },
                    {
                        "description": "Coverage report example (file)",
                        "path": "doc/report_file_example.png"
                    },
                    {
                        "description": "Coverage check example (passing)",
                        "path": "doc/check_result_pass.png"
                    },
                    {
                        "description": "Coverage check example (failing)",
                        "path": "doc/check_result_fail.png"
                    }
                ],
                "environment": {
                    "sdk": ">=3.0.0 <4.0.0"
                },
                "dependencies": {
                    "args": "^2.4.2",
                    "collection": "^1.18.0",
                    "html": "^0.15.4",
                    "io": "^1.0.4",
                    "meta": "^1.9.1",
                    "path": "^1.8.3",
                    "process": "^4.2.4",
                    "pub_updater": "^0.3.1",
                    "universal_io": "^2.2.2"
                },
                "dev_dependencies": {
                    "build": "^2.4.1",
                    "build_config": "^1.1.1",
                    "build_runner": "^2.4.6",
                    "build_verify": "^3.1.0",
                    "csslib": "^1.0.0",
                    "mocktail": "^1.0.0",
                    "pubspec_parse": "^1.2.3",
                    "test": "^1.24.6",
                    "very_good_analysis": "^5.0.0+1",
                    "package_assets_generator": {
                        "path": "../package_assets_generator"
                    },
                    "package_data_generator": {
                        "path": "../package_data_generator"
                    }
                },
                "executables": {
                    "coverde": null
                }
            },
            "archive_url": "https://pub.dev/api/archives/coverde-0.2.0%2B2.tar.gz",
            "archive_sha256": "09d909f35accb2f1add449eba33b4afd835aad30ef039b34d6db65e52fe8fca8",
            "published": "2023-08-18T07:52:19.455101Z"
        }
    ]
}
            ''',
              HttpStatus.ok,
            ),
          ),
        );
        final progress = _MockProgress();
        when(() => logger.progress(any())).thenReturn(progress);
        await packageVersionManager.promptUpdate();
        verify(
          () => logger.write(
            '''
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃                                                           ┃
┃         ${lightYellow.wrap('A new version of `coverde` is available!')}          ┃
┃                     ${lightGray.wrap('0.2.0+1')} \u2192 ${lightGreen.wrap('0.2.0+2')}                     ┃
┃  Run ${wrapWith('dart pub global activate coverde 0.2.0+2', [
                  lightCyan,
                  styleBold,
                ])} to update.  ┃
┃                                                           ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
''',
          ),
        ).called(1);
      });

      test(
          'warns the user '
          'if the package is not globally installed', () async {
        File(lockFilePath).writeAsStringSync('''
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  args:
    dependency: transitive
    description:
      name: args
      sha256: d0481093c50b1da8910eb0bb301626d4d8eb7284aa739614d2b394ee09e3ea04
      url: "https://pub.dev"
    source: hosted
    version: "2.7.0"
  async:
    dependency: transitive
    description:
      name: async
      sha256: "758e6d74e971c3e5aceb4110bfd6698efc7f501675bcfe0c775459a8140750eb"
      url: "https://pub.dev"
    source: hosted
    version: "2.13.0"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: "2f5709ae4d3d59dd8f7cd309b4e023046b57d8a6c82130785d2b0e5868084e76"
      url: "https://pub.dev"
    source: hosted
    version: "1.19.1"
  csslib:
    dependency: transitive
    description:
      name: csslib
      sha256: "09bad715f418841f976c77db72d5398dc1253c21fb9c0c7f0b0b985860b2d58e"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.2"
  file:
    dependency: transitive
    description:
      name: file
      sha256: "1b92bec4fc2a72f59a8e15af5f52cd441e4a7860b49499d69dfa817af20e925d"
      url: "https://pub.dev"
    source: hosted
    version: "6.1.4"
  html:
    dependency: transitive
    description:
      name: html
      sha256: "6d1264f2dffa1b1101c25a91dff0dc2daee4c18e87cd8538729773c073dbf602"
      url: "https://pub.dev"
    source: hosted
    version: "0.15.6"
  http:
    dependency: transitive
    description:
      name: http
      sha256: "87721a4a50b19c7f1d49001e51409bddc46303966ce89a65af4f4e6004896412"
      url: "https://pub.dev"
    source: hosted
    version: "1.6.0"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      sha256: "178d74305e7866013777bab2c3d8726205dc5a4dd935297175b19a23a2e66571"
      url: "https://pub.dev"
    source: hosted
    version: "4.1.2"
  io:
    dependency: transitive
    description:
      name: io
      sha256: dfd5a80599cf0165756e3181807ed3e77daf6dd4137caaad72d0b7931597650b
      url: "https://pub.dev"
    source: hosted
    version: "1.0.5"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      sha256: "1ce844379ca14835a50d2f019a3099f419082cfdd231cd86a142af94dd5c6bb1"
      url: "https://pub.dev"
    source: hosted
    version: "4.9.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: "23f08335362185a5ea2ad3a4e597f1375e78bce8a040df5c600c8d3552ef2394"
      url: "https://pub.dev"
    source: hosted
    version: "1.17.0"
  path:
    dependency: transitive
    description:
      name: path
      sha256: "75cca69d1490965be98c73ceaea117e8a04dd21217b37b292c9ddbec0d955bc5"
      url: "https://pub.dev"
    source: hosted
    version: "1.9.1"
  platform:
    dependency: transitive
    description:
      name: platform
      sha256: "5d6b1b0036a5f331ebc77c850ebc8506cbc1e9416c27e59b439f917a902a4984"
      url: "https://pub.dev"
    source: hosted
    version: "3.1.6"
  process:
    dependency: transitive
    description:
      name: process
      sha256: "53fd8db9cec1d37b0574e12f07520d582019cb6c44abf5479a01505099a34a09"
      url: "https://pub.dev"
    source: hosted
    version: "4.2.4"
  pub_semver:
    dependency: transitive
    description:
      name: pub_semver
      sha256: "5bfcf68ca79ef689f8990d1160781b4bad40a3bd5e5218ad4076ddb7f4081585"
      url: "https://pub.dev"
    source: hosted
    version: "2.2.0"
  pub_updater:
    dependency: transitive
    description:
      name: pub_updater
      sha256: b06600619c8c219065a548f8f7c192b3e080beff95488ed692780f48f69c0625
      url: "https://pub.dev"
    source: hosted
    version: "0.3.1"
  source_span:
    dependency: transitive
    description:
      name: source_span
      sha256: "254ee5351d6cb365c859e20ee823c3bb479bf4a293c22d17a9f1bf144ce86f7c"
      url: "https://pub.dev"
    source: hosted
    version: "1.10.1"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      sha256: "921cd31725b72fe181906c6a94d987c78e3b98c2e205b397ea399d4054872b43"
      url: "https://pub.dev"
    source: hosted
    version: "1.4.1"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      sha256: "7f554798625ea768a7518313e58f83891c7f5024f88e46e7182a4558850a4b8e"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.2"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      sha256: f9049c039ebfeb4cf7a7104a675823cd72dba8297f264b6637062516699fa006
      url: "https://pub.dev"
    source: hosted
    version: "1.4.0"
  universal_io:
    dependency: transitive
    description:
      name: universal_io
      sha256: f63cbc48103236abf48e345e07a03ce5757ea86285ed313a6a032596ed9301e2
      url: "https://pub.dev"
    source: hosted
    version: "2.3.1"
  web:
    dependency: transitive
    description:
      name: web
      sha256: "868d88a33d8a87b18ffc05f9f030ba328ffefba92d6c127917a2ba740f9cfe4a"
      url: "https://pub.dev"
    source: hosted
    version: "1.1.1"
sdks:
  dart: ">=3.6.0 <4.0.0"
''');
        final progress = _MockProgress();
        when(() => logger.progress(any())).thenReturn(progress);
        await packageVersionManager.promptUpdate();
        verify(
          () => logger.warn(
            'No global package installation info found.',
          ),
        ).called(1);
      });

      test(
          'warns the user '
          'if there is no newer compatible version', () async {
        File(lockFilePath).writeAsStringSync('''
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  args:
    dependency: transitive
    description:
      name: args
      sha256: d0481093c50b1da8910eb0bb301626d4d8eb7284aa739614d2b394ee09e3ea04
      url: "https://pub.dev"
    source: hosted
    version: "2.7.0"
  async:
    dependency: transitive
    description:
      name: async
      sha256: "758e6d74e971c3e5aceb4110bfd6698efc7f501675bcfe0c775459a8140750eb"
      url: "https://pub.dev"
    source: hosted
    version: "2.13.0"
  collection:
    dependency: transitive
    description:
      name: collection
      sha256: "2f5709ae4d3d59dd8f7cd309b4e023046b57d8a6c82130785d2b0e5868084e76"
      url: "https://pub.dev"
    source: hosted
    version: "1.19.1"
  coverde:
    dependency: "direct main"
    description:
      name: coverde
      sha256: "09d909f35accb2f1add449eba33b4afd835aad30ef039b34d6db65e52fe8fca8"
      url: "https://pub.dev"
    source: hosted
    version: "0.2.0+1"
  csslib:
    dependency: transitive
    description:
      name: csslib
      sha256: "09bad715f418841f976c77db72d5398dc1253c21fb9c0c7f0b0b985860b2d58e"
      url: "https://pub.dev"
    source: hosted
    version: "1.0.2"
  file:
    dependency: transitive
    description:
      name: file
      sha256: "1b92bec4fc2a72f59a8e15af5f52cd441e4a7860b49499d69dfa817af20e925d"
      url: "https://pub.dev"
    source: hosted
    version: "6.1.4"
  html:
    dependency: transitive
    description:
      name: html
      sha256: "6d1264f2dffa1b1101c25a91dff0dc2daee4c18e87cd8538729773c073dbf602"
      url: "https://pub.dev"
    source: hosted
    version: "0.15.6"
  http:
    dependency: transitive
    description:
      name: http
      sha256: "87721a4a50b19c7f1d49001e51409bddc46303966ce89a65af4f4e6004896412"
      url: "https://pub.dev"
    source: hosted
    version: "1.6.0"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      sha256: "178d74305e7866013777bab2c3d8726205dc5a4dd935297175b19a23a2e66571"
      url: "https://pub.dev"
    source: hosted
    version: "4.1.2"
  io:
    dependency: transitive
    description:
      name: io
      sha256: dfd5a80599cf0165756e3181807ed3e77daf6dd4137caaad72d0b7931597650b
      url: "https://pub.dev"
    source: hosted
    version: "1.0.5"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      sha256: "1ce844379ca14835a50d2f019a3099f419082cfdd231cd86a142af94dd5c6bb1"
      url: "https://pub.dev"
    source: hosted
    version: "4.9.0"
  meta:
    dependency: transitive
    description:
      name: meta
      sha256: "23f08335362185a5ea2ad3a4e597f1375e78bce8a040df5c600c8d3552ef2394"
      url: "https://pub.dev"
    source: hosted
    version: "1.17.0"
  path:
    dependency: transitive
    description:
      name: path
      sha256: "75cca69d1490965be98c73ceaea117e8a04dd21217b37b292c9ddbec0d955bc5"
      url: "https://pub.dev"
    source: hosted
    version: "1.9.1"
  platform:
    dependency: transitive
    description:
      name: platform
      sha256: "5d6b1b0036a5f331ebc77c850ebc8506cbc1e9416c27e59b439f917a902a4984"
      url: "https://pub.dev"
    source: hosted
    version: "3.1.6"
  process:
    dependency: transitive
    description:
      name: process
      sha256: "53fd8db9cec1d37b0574e12f07520d582019cb6c44abf5479a01505099a34a09"
      url: "https://pub.dev"
    source: hosted
    version: "4.2.4"
  pub_semver:
    dependency: transitive
    description:
      name: pub_semver
      sha256: "5bfcf68ca79ef689f8990d1160781b4bad40a3bd5e5218ad4076ddb7f4081585"
      url: "https://pub.dev"
    source: hosted
    version: "2.2.0"
  pub_updater:
    dependency: transitive
    description:
      name: pub_updater
      sha256: b06600619c8c219065a548f8f7c192b3e080beff95488ed692780f48f69c0625
      url: "https://pub.dev"
    source: hosted
    version: "0.3.1"
  source_span:
    dependency: transitive
    description:
      name: source_span
      sha256: "254ee5351d6cb365c859e20ee823c3bb479bf4a293c22d17a9f1bf144ce86f7c"
      url: "https://pub.dev"
    source: hosted
    version: "1.10.1"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      sha256: "921cd31725b72fe181906c6a94d987c78e3b98c2e205b397ea399d4054872b43"
      url: "https://pub.dev"
    source: hosted
    version: "1.4.1"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      sha256: "7f554798625ea768a7518313e58f83891c7f5024f88e46e7182a4558850a4b8e"
      url: "https://pub.dev"
    source: hosted
    version: "1.2.2"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      sha256: f9049c039ebfeb4cf7a7104a675823cd72dba8297f264b6637062516699fa006
      url: "https://pub.dev"
    source: hosted
    version: "1.4.0"
  universal_io:
    dependency: transitive
    description:
      name: universal_io
      sha256: f63cbc48103236abf48e345e07a03ce5757ea86285ed313a6a032596ed9301e2
      url: "https://pub.dev"
    source: hosted
    version: "2.3.1"
  web:
    dependency: transitive
    description:
      name: web
      sha256: "868d88a33d8a87b18ffc05f9f030ba328ffefba92d6c127917a2ba740f9cfe4a"
      url: "https://pub.dev"
    source: hosted
    version: "1.1.1"
sdks:
  dart: ">=3.6.0 <4.0.0"
''');
        when(() => httpClient.get(any())).thenAnswer(
          (_) async => http.Response(
            '''
{
    "name": "coverde",
    "latest": {
        "version": "0.2.0+2",
        "pubspec": {
            "name": "coverde",
            "description": "A CLI for basic coverage trace files manipulation. Validate minimum coverage, filter trace files data by tested file paths and generate HTML coverage reports.",
            "version": "0.2.0+2",
            "homepage": "https://github.com/mrverdant13/coverde",
            "repository": "https://github.com/mrverdant13/coverde/tree/main/packages/coverde_cli",
            "issue_tracker": "https://github.com/mrverdant13/coverde/issues",
            "topics": [
                "test",
                "testing",
                "coverage",
                "lcov"
            ],
            "screenshots": [
                {
                    "description": "Coverage report example (directory)",
                    "path": "doc/report_directory_example.png"
                },
                {
                    "description": "Coverage report example (file)",
                    "path": "doc/report_file_example.png"
                },
                {
                    "description": "Coverage check example (passing)",
                    "path": "doc/check_result_pass.png"
                },
                {
                    "description": "Coverage check example (failing)",
                    "path": "doc/check_result_fail.png"
                }
            ],
            "environment": {
                "sdk": ">=3.0.0 <4.0.0"
            },
            "dependencies": {
                "args": "^2.4.2",
                "collection": "^1.18.0",
                "html": "^0.15.4",
                "io": "^1.0.4",
                "meta": "^1.9.1",
                "path": "^1.8.3",
                "process": "^4.2.4",
                "pub_updater": "^0.3.1",
                "universal_io": "^2.2.2"
            },
            "dev_dependencies": {
                "build": "^2.4.1",
                "build_config": "^1.1.1",
                "build_runner": "^2.4.6",
                "build_verify": "^3.1.0",
                "csslib": "^1.0.0",
                "mocktail": "^1.0.0",
                "pubspec_parse": "^1.2.3",
                "test": "^1.24.6",
                "very_good_analysis": "^5.0.0+1",
                "package_assets_generator": {
                    "path": "../package_assets_generator"
                },
                "package_data_generator": {
                    "path": "../package_data_generator"
                }
            },
            "executables": {
                "coverde": null
            }
        },
        "archive_url": "https://pub.dev/api/archives/coverde-0.2.0%2B2.tar.gz",
        "archive_sha256": "09d909f35accb2f1add449eba33b4afd835aad30ef039b34d6db65e52fe8fca8",
        "published": "2023-08-18T07:52:19.455101Z"
    },
    "versions": [
    ]
}
            ''',
            HttpStatus.ok,
          ),
        );
        final progress = _MockProgress();
        when(() => logger.progress(any())).thenReturn(progress);
        await packageVersionManager.promptUpdate();
        verify(
          () => logger.warn(
            'No newer compatible version of `coverde` is available.',
          ),
        ).called(1);
      });
    });
  });
}
