name: readmes_resolver
description: A tool to resolve README files.
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  args: ^2.7.0
  collection: ^1.19.1
  coverde:
    path: ../../packages/coverde_cli/
  path: ^1.9.1
  recase: ^4.1.0

dev_dependencies:
  very_good_analysis: ^10.0.0
