name: E2E testing

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  workflow_dispatch: {}

jobs:
  e2e:
    name: E2E testing
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Install Flutter
        uses: subosito/flutter-action@v2
      - name: Install ripple
        uses: ./.github/actions/install-dart-cli
        with:
          package: >-
            ripple_cli@{git: {url: https://github.com/mrverdant13/ripple.git, ref: c7c50f41fd43570316a1d85bdcacf31e0db4f2df}}
      - name: Bootstrap packages
        run: |
          dart pub get
          ripple exec --fail-fast -- {{dart}} pub get
      - name: Run E2E tests
        run: ripple run test.e2e.ci --fail-fast
