name: Resolve READMEs

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/resolve_readmes.yaml
      - packages/coverde_cli/**
      - ripple.yaml
      - README.md
      - tools/readmes_resolver/**

jobs:
  resolve-cli-readme:
    name: Resolve CLI README
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Install dart
        uses: dart-lang/setup-dart@v1
      - name: Install ripple
        uses: ./.github/actions/install-dart-cli
        with:
          package: >-
            ripple_cli@{git: {url: https://github.com/mrverdant13/ripple.git, ref: 72a3a97b2615fe1b133573320bdb187335f8adf4}}
      - name: Bootstrap packages
        run: |
          dart pub get
          ripple exec --fail-fast -- dart pub get
      - name: Resolve CLI README file
        run: ripple run docs.cli
      - name: Create PR
        uses: peter-evans/create-pull-request@v8
        with:
          base: main
          add-paths: |
            ./packages/coverde_cli/README.md
          branch: docs/update-cli-readme
          commit-message: "docs: update CLI README"
          title: "docs: update CLI README"
          body: Update CLI README.
          delete-branch: true
          author: Coverde Bot <coverde.bot@users.noreply.github.com>
          committer: Coverde Bot <coverde.bot@users.noreply.github.com>
          assignees: mrverdant13
          reviewers: mrverdant13
